<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [3]:
#You need to use def, ':' and indent for function's code block
#You may or may not insert parameters


def is_odd(n):
    if n % 2 != 0:
        return True
    else: 
        return False
    
print(is_odd(4))    
print('') #-------
print(is_odd(7))

#You can also return an ordered pair

import numpy as np

np_array = np.array([1,2,3,4,5])

def max_min(array):
    return array.max(), array.min()

print(max_min(np_array))

def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

print(basic_stats([1,2,3,4,5]))



False

True
(5, 1)
(1, 5, 3.0)


### 1.2 Named functions that don’t return

In [28]:
#Functions with no return value by default hold None value

def foo():
    1 + 2
    
print(foo())    

None


### 1.3 Anonymous functions

In [31]:
#Lambda functions are suitable for short one liners
#Lambda functions return the value of the last statement

list_2d = [[1,2,3],[4,5,6],[7,8,9],[0,2,1],[1,1,1],[0,0,9]]

print(sorted(list_2d, key = lambda x:sum(x)))

print('')

print(sorted(list_2d, key = lambda x:x[-1]))

[[0, 2, 1], [1, 1, 1], [1, 2, 3], [0, 0, 9], [4, 5, 6], [7, 8, 9]]

[[0, 2, 1], [1, 1, 1], [1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 0, 9]]


### 1.4 Optional arguments

In [48]:
#We can define our functions with a default value for our parameter, so it has always something to work with
#This allows us to run the function without an argument

def foo(x=2):
    if x > 2:
        return True
    else:
        return False
    
print(foo())
print(foo(3))



False
True


In [57]:
#Extra info: Documentation for print

#   ?print

#    Docstring:
#    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
#
#    Prints the values to a stream, or to sys.stdout by default.
#    Optional keyword arguments:
#    file:  a file-like object (stream); defaults to the current sys.stdout.
#    sep:   string inserted between values, default a space.
#    end:   string appended after the last value, default a newline.
#    flush: whether to forcibly flush the stream.
#    Type:      builtin_function_or_method

print("2", "is", "even", sep = '--')

for i in range(5):
    print(i, end=' ')

2--is--even
0 1 2 3 4 

## 2 The importance of functions?

### 2.1 An argument for functions

Functions can be used for abstraction of details, reusability of code and maintainability of code


### 2.2 A word of caution

Word of caution = I have seen instances where functions are abused; for example, by trying to do too much or having too many arguments. They can also be overused. Having too many functions can make it difficult to read your code and also increase computational overheads. You will get a better feel for when to use functions with experience, but please bear in mind that functions can be misused.


## Exercise 1 :  Do you know why?

In the case where name == Batman, the if <condition> becomes True and the code block is executed, returning **'Hello Batman! So, nice to meet you!'**. Once Python sees the return line, it jumps out of the function with this return value. 
    
In all other cases, the if <condition> becomes False and the code block is not executed, therefore it goes past the 'function body' and goes to the last return line. The last line contains a return statement, so when Pythom sees it, it jumps out of the function with this return value, which is **f'Hello {name}!**

## Exercise 2 :  Calculator functions

In [23]:
def add(x,y):
    return x+y
def subtract(x,y):
    return x - y
def multiply(x,y):
    return x*y
def divide(x,y):
    if type(x) == np.ndarray and type(y) == np.ndarray:
        if y.all()== 0:
            exit()
        else:
            return x/y
    elif type(x) == int and type(y) == int:
        return x/y
    
x= np.array([36, 34, 44, 76, 27])
y= np.array([64, 66, 56, 24, 73])

print(add(x,y))

print('')

print(subtract(x,y))

print('')

print(multiply(x,y))

print('')

print(divide(x,y))






[100 100 100 100 100]

[-28 -32 -12  52 -46]

[2304 2244 2464 1824 1971]

[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [62]:
def max_info(numbers):
    numbers = np.array(numbers)
    return numbers.max(), numbers.argmax()  #Returns maximum number in list, index of the maximum number in the list

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

print(max_info(numbers))



(83, 2)
