<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
#Subsetting is the process of selecting a subset 

#Indexing and Slicing are 2 means of which you can select your subset

#[x : y : z]

#x = start, y = end(inclusive), z = step

import numpy as np

list_1 = [1,2,3,4,5]
array_1 = np.array(list_1)

print(list_1[::])

print(array_1[::])

print(list_1[::-1])

print(array_1[::-1])

print(list_1[1::2])

print(array_1[1::2])

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[5, 4, 3, 2, 1]
[5 4 3 2 1]
[2, 4]
[2 4]


### 1.2 Subsetting by masking (Arrays only)

In [15]:
array_1 = np.array([1,2,3,4,5,6])

mask_a1 = (array_1 > 2)

print(mask_a1)

#Subsetting by masking only reveals the true data type

print(array_1[mask_a1])

#or a more succint approach 

print(array_1[array_1 > 2])

#Bitwise operators can also be implemented

print(array_1[~(array_1>2)]) #~ refers to not

print(array_1[(array_1>2)&(array_1<5)]) #& refers to and 

print(array_1[(array_1>2)|(array_1 <5)]) #| refers to or



[False False  True  True  True  True]
[3 4 5 6]
[3 4 5 6]
[1 2]
[3 4]
[1 2 3 4 5 6]


### 1.3 Indexing & Slicing 2D Lists

In [41]:
#Lists

list_1 = [[1,2,3],[4,5,6],[7,8,9]]

print(list_1[1])

print(list_1[1][-1])

print(list_1[:2])

print(list_1[:2][0])

print(list_1[::-1][0])

print("   ")






[4, 5, 6]
6
[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
[7, 8, 9]
   


### 1.4 Indexing & Slicing 2D Arrays

In [42]:
#Arrays

array_1 = np.array(list_1)

print(array_1[0])

print(array_1[0,0]) #unlike lists, everything is enclosed in one square brackets

print(array_1[:2])

print(array_1[:2,0]) #unlike list, this gives the first element of every sublist

print(array_1[::-1,-1])


[1 2 3]
1
[[1 2 3]
 [4 5 6]]
[1 4]
[9 6 3]


### 1.5 Growing lists

In [81]:
#Lists are useful because we can easily grow their size. Numpy arrays are useful for maths, especially when size is constant

#Ways to grow a list

list_1 = [1,2,3]

#Multiplication

list_2 = list_1 * 2
print(list_2)

#Concatenation

list_2 = list_1 + [2]
print(list_2)

list_2 += [2,2,2]
print(list_2)

#Note: For prepending, add the intended list you want to add in the front

list_2 = [2,2,2] + list_1
print(list_2)

#Append

list_1.append(4)
print(list_1)






[1, 2, 3, 1, 2, 3]
[1, 2, 3, 2]
[1, 2, 3, 2, 2, 2, 2]
[2, 2, 2, 1, 2, 3]
[1, 2, 3, 4]
[3, 2, 3, 4]


## 2 Some loose ends

### 2.1 Tuples

In [77]:
#Tuples are like lists, except they use paranthesis and they cannot be modified

tuple_1 = (1,2,3)

print(tuple_1)

print(tuple_1[0])

#You cannot change the data of the list using indexing

#tuple_1[0] = 7 ---> 'tuple' object does not support item assignment




(1, 2, 3)
1


### 2.2 Be VERY careful when copying

In [88]:
#Variables in Python have subtle features that require you to be mindful when making copies of lists and arrays.

#When you want to copy a list or a tuple, do the following

x = [1,2,3]

y = x.copy()

print(y)

[1, 2, 3]


## Exercise 1 :  Total recall?

| **Term**    | **Description**                                                                |
| :---------- |                                                                                |
| Subsetting  | Process of selecting a suitable subset of a list-like object                   |
| Indexing    | Selecting an individual element                                                |
| Slicing     | Selecting a range of elements                                                  |
| Masking     | *A method of subsetting that works only for arrays* *Reveals all True subsets* |

## Exercise 2 :  Show me the ‘odd’ letters

In [98]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_1 = np_array_2d[::,0]

print(np_array_1)

list_1 = []

for i in np_array_1:
    i = int(i)
    list_1 += [i]
    
np_array_1 = np.array(list_1)

np_array_mask = (np_array_1 % 2 != 0)

np_arrayz = np_array_2d[np_array_mask]

print(np_arrayz[::,1])





['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
['A' 'C' 'E' 'G' 'I']
