<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [16]:
#The 3 basic ways of storing data are using lists, numpy arrays and dictionaries

#Dictionaries uses a kay and an associated value separated by :

#Order matters for list and arrays

#Which data storage stratey you choose will depend on the problem you are trying to solve

import numpy as np

list_superhero_names = ['spiderman','thor','captain america']
list_superhero_real_names = ['peter','thor','steve']

array_superheronames = np.array(['spiderman','thor','captain america'])
array_superhero_real_names = np.array(['peter','thor','steve'])

dict_superheroinfo = {
    
        'spiderman':'peter',
        'thor':'thor',
        'captain america':'steve'
}

print(dict_superheroinfo)



{'spiderman': 'peter', 'thor': 'thor', 'captain america': 'steve'}


### 1.2 Accessing data from a list (or array)

In [49]:
#We can access data from a list or an array using indexing

#In python, indexing start from 0

#Negative indexing starts from the back, useful when you want to retrieve data at the end but you don't know the length of the list/array
    

listz = ['a','b','c','d','e']
array = np.array(['w','x','y','z'])

print(listz[2])

print(listz[-1])

print(array[3])

c
e
z


### 1.3 Accessing data from a dictionary

In [30]:
#To access value from a dictionary, you need to 'index' it's key

#dictionary_name[key]---> value

dictionary = {1:'black',
              2:'white',
              3:'green',
              4:'red'
             }

print(dictionary[1])

print(dictionary[4])
              

#To access all the keys, use dictionary_name.keys() function

#To access all the values, use dictionary_name.values() function

print(dictionary.keys())

print(dictionary.values())



black
red
dict_keys([1, 2, 3, 4])
dict_values(['black', 'white', 'green', 'red'])


### 1.4 Higher dimensional lists

In [32]:
TwoD_List = [['spiderman','peter'],['thor','thor'],['captain america','steve']]

print(TwoD_List)

#A 2d list is basically a list whose elements are lists

#A 3d list is a list whose elements are 2d lists


[['spiderman', 'peter'], ['thor', 'thor'], ['captain america', 'steve']]


## 2 Lists vs. Arrays

### 2.1 Size

In [38]:
#len function returns the length of list and arrays respectively

TwoD_Array = np.array(TwoD_List)

print(len(TwoD_List))

print(len(TwoD_Array))

#For arrays, there is an attribute called shape

#For 2D arrays, the shape attribute returns a tuple

#The tuple is of the form (x, y), where x = no. of rows and y = no. of columns

print(TwoD_Array.shape)

#Helpful to think of 2D arrays as matrices

#Note that shape is not a function, it is an attribute, hence the absence of paranthesis




3
3
(3, 2)


### 2.2 Arrays are fussy about type

In [40]:
#Numpy arrays only hold data of the same type

array_1 = np.array([1,2,'a'])

print(array_1) #Notice how the output shows 1 and 2 as strings and not integers

#Later on, you will learn how to change types using a 'hidden' function --> astypes()



['1' '2' 'a']


### 2.3 Adding a number

In [45]:
#You cannot perform mathematical addition ('entry addition') for your list

list_1 = [1,2,3]

#list = list + 4

#print(list) ---> TypeError: can only concatenate list (not "int") to list

#However for arrays, you can add numbers

array_2 = np.array(list)

array_2 = array_2 + 4

print(array_2)

[5 6 7]


### 2.4 Adding another list

In [55]:
#Adding one list to another is basically concatenation

list_1 = [1,2,3]

list_1 += list_1

print(list_1)

#Adding an array to another is basically 'entry addition'

list_1 = [1,2,3]

array_1 = np.array(list_1)
array_2 = array_1 + array_1



print(array_2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


### 2.5 Multiplying by a Number

In [68]:
#Multiplying a list by an integer basically scales the no. of elements of the list by a factor of the integer

list_1 = [1,2,3,4]

list_2 = ['a','b']

print(list_1*2)

print(list_1*0) #returns an empty list

print(list_2*2)

#print(list_1*0.5) ---> TypeError: can't multiply sequence by non-int of type 'float'

#Multiplying an array by a real number basically scales the individual entry by that number

array_1 = np.array(list_1)

print(array_1)

print(array_1*2)

print(array_1*0.5)

print(array_1*0)

print(array_1*-2)

array_2d = np.array([[1,2],[3,4]])

print(array_2d)

print(array_2d*2)

array_2 = np.array(['a','b'])

#print(array_2*2) ---> UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('int64')) -> None

#If i am not wrong, multiplying by a number for arrays only work if the entries are also numbers

[1, 2, 3, 4, 1, 2, 3, 4]
[]
['a', 'b', 'a', 'b']
[1 2 3 4]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 0 0 0]
[-2 -4 -6 -8]
[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


### 2.6 Squaring

In [72]:
#You cannot raise a list to an exponent

list_1 = [1,2,3]

#print(list_1**2) ---> TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

#For arrays though, you can. Raising an array to an exponents basically raises every entry of the array to that exp

array_1 = np.array(list_1)

print(array_1**2)

#Again, i think it only works if all the entries in the array are numbers



[1 4 9]


### 2.7 Asking questions

In [80]:
#You can use boolean operators on lists and arrays 

list_1 = [1,2,3]

print(list_1 == 9) #Asking whether list_1 holds the value 9, which is false

list_1 = [1]

print(list_1 == 1) 

list_1 = [1,2,3]

#print(list_1 > 3) ---> TypeError: '>' not supported between instances of 'list' and 'int'

array_1 = np.array(list_1)

print(array_1 == 1) #Asking whether each entry of the array is equals to 1

print(array_1 < 3) #Asking whether each entry of the array is strictly smaller than 3

False
False
[ True False False]
[ True  True False]


### 2.8 Mathematics

In [85]:
#Given a list, you can find it's Sum, Max, Min and Mean using python base functions

list_1 = [1,2,3]

print(sum(list_1))

print(max(list_1))

print(min(list_1))

print(mean(list_1))

array_1 = np.array(list_1)

print(sum(array_1))

print(max(array_1))

print(min(array_1))

print(mean(array_1))


6
3
1
2.0
6
3
1
2.0


## Exercise 1 :  Total recall?

1. We can access the data of both lists and arrays by indexing and list and arrays both have dimensions
2. You cannot raise a list to an exponent but you can do so for arrays(if the arrays entry are numbers) and you cannot add a number to your list but you can do so for arrays(if the arrays entry are numbers). Also, adding a number to an array will result in adding the number to every entry in the array.
3. A dictionary is a data type that stores information as a key to value pair. The key and value are separated by ':'




## Exercise 2 :  Index me

In [96]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

for i in py_list:
    if int(i[1])%2 != 0:
        print(i)

a1
c3
e5
g7
i9
j10


## Exercise 3 :  Capitalise Heros

In [99]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  


for i in superhero_info.keys():
    superhero_info[i] = superhero_info[i].upper()

print(superhero_info)

    

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [98]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

numbers = np.array(numbers)

numbers = (numbers==1)

counter = 0
for i in numbers:
    if i == True:
        counter+= 1
    else:
        continue
        
print(counter)



9
